#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace GameplayAbilities { struct FServerAbilityRPCBatch; }

namespace BPVE_FishingListItem { class UBPVE_FishingListItem_C; }

namespace BPVE_FishingListItem_0 { class UBPVE_FishingListItem_C; }

